### ISSUE TITLE
영문화 계획이 있으신지 궁금합니다

### ISSUE THREAD

**Issue by sr4dev** [seonghwan-dev/Reference#2]
Reference를 사내 프로젝트에 적용해보고자 하는데 한국어 사용자가 아닌 사람들이 많은 탓에 고민중입니다.
메뉴나 각종 문구에 한글로 적힌 문장들을 영문화시킬 계획이 있으신가요?

그리고 계획이 있으시다면 부족한 영어 실력이지만 영문화에 코드기여를 해보고 싶습니다.

**Comment by seonghwan-dev** [comment]
마침 구상 중에 있습니다. 

어느 정도 안정화 후 작업 할 생각이었는데, 이제 슬슬 작업해도 괜찮을 시기인 듯 합니다.
컴파일타임과 런타임 로컬라이징 중에 고민중에 있습니다. 

어떤 방식으로든 기여는 환영입니다!

**Comment by seonghwan-dev** [comment]
@sr4dev 
`0.1.0` 버전부터 언어 별 대응이 가능합니다.

**Comment by sr4dev** [comment]
앗 엄청 빠르네요! 감사합니다!! 이 이슈는 클로즈 하겠습니다

**Comment by seonghwan-dev** [comment]
넵, 이제 대략 구조가 잡혀서 언어 추가와 편의기능 넣으면 될 것 같습니다.
